const menu = [
    {
        id: 1,
        title: 'Dose',
        category: 'breakfast',
        price: 45,
        img: './images/dosa.jpg',
        desc: 'A dosa is a thin pancake or crepe, originating from South India, made from a fermented batter predominantly consisting of lentils and rice.',
      },
    {
      id: 2,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 40,
      img: './images/item-1.jpeg',
      desc: `A pancake is a flat cake, often thin and round, prepared from a starch-based batter that may contain eggs, milk and butter and cooked on a hot surface,often frying with oil or butter.`,
    },
    {
      id: 3,
      title: 'Strawberry milkshake',
      category: 'Snacks',
      price: 60,
      img: './images/item-3.jpeg',
      desc: `A Strawberry milkshake is a sweet drink made by blending milk, ice cream, and flavorings of Strawberry and whole fruit into a thick, sweet, cold mixture.`,
    },
    {
      id: 4,
      title: 'Bread Omlet',
      category: 'breakfast',
      price: 40,
      img: './images/item-4.jpeg',
      desc: 'Roasted Bread with butter or ghee with Omlet on it and served hot',
    },
    {
      id: 5,
      title: 'Veg Biriyani',
      category: 'lunch',
      price: 150,
      img: './images/vegbiriyani.jpg',
      desc: `Vegetable biryani is an aromatic rice dish made with basmati rice, mix veggies, herbs & biryani spices `,
    },
    {
      id: 6,
      title: 'Oreo dream',
      category: 'Snacks',
      price: 90,
      img: './images/item-6.jpeg',
      desc: `A Oreo milkshake is a sweet drink made by blending milk, ice cream, Oreo and a thick, sweet, cold mixture.`,
    },
    {
      id: 7,
      title: 'idli',
      category: 'breakfast',
      price: 30,
      img: './images/idle.jpg',
      desc: `Idli is a hearty, satisfying, comforting and a healthy meal of soft fluffy idlis served with savory, spiced and lightly tangy sambar `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'Snacks',
      price: 50,
      img: './images/item-8.jpeg',
      desc: `A sandwich, consisting of one or more cooked patties of ground meat, placed inside a sliced bread roll or bun with French Fries  `,
    },
    {
      id: 9,
      title: 'paratha',
      category: 'breakfast',
      price: 30,
      img: './images/paratha.jpg',
      desc: `Paratha is a layers of cooked dough fried with ghee on Pan and served hot`,
    },
    {
        id: 10,
        title: 'Chicken LollyPop',
        category: 'dinner',
        price: 50,
        img: './images/img1.jpg',
        desc: `Fried and Rosted Chicken Leg Piece with Spieces on it and served hot`,
    },
    {
        id: 11,
        title: 'Chicken Biriyani',
        category: 'dinner',
        price: 200,
        img: './images/img2.jpg',
        desc: `Chicken biryani is a popular dish in India. It is made with chicken, rice, spices, saffron, and vegetables. The dish is served with a side of pickled or fresh onion slices. `,
    },
    {
        id: 12,
        title: 'Gulab Jamun',
        category: 'Snacks',
        price: 30,
        img: './images/img3.jpg',
        desc: `Gulab Jamun is a milk-solid-based sweet which is round in shape and brown in color`,
    },
    {
        id: 13,
        title: 'Samosa',
        category: 'Snacks',
        price: 30,
        img: './images/img4.jpg',
        desc: `A samosa is a  baked pastry with a savory filling like spiced potatoes and served hot`,
    },
    {
        id: 14,
        title: 'Butter naan and Shahi Panner',
        category: 'dinner',
        price: 80,
        img: './images/butternaan.jpg',
        desc: `Butter Naan is made of flour but softer in texture due to the yeast and butter used `,
    },
    {
        id: 15,
        title: 'Thali',
        category: 'lunch',
        price: 100,
        img: './images/thali.jpg',
        desc: `All combinations of South indian food in Small quantity and served hot`,
    },
    {
        id: 16,
        title: 'Curd Rice',
        category: 'dinner',
        price: 100,
        img: './images/curdrice.jpg',
        desc: `Curd Rice is a mixture of curd with Rice serverd and served hot`,
    },
    {
        id: 17,
        title: 'Mutton Biriyani',
        category: 'dinner',
        price: 200,
        img: './images/mutton.png',
        desc: 'Mutton Biryani is a rice-based dish made with spices and mutton, eggs or vegetables. The name is derived from the Persian word beryā, meaning fried,roasted. ',
    }

  ];
  export default menu;
  